fix: proper notemp specification in the profiles / tests
zavolanlab/zarp pull request #56
Opened 2022-03-15 23:41 UTC by AngryMaciek

## Description

Please include a summary of the change and which issue is fixed.  
Please also include relevant motivation and context.  
List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation updated

## Checklist:

- [ ] My code changes follow the style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have updated the project's documentation

2022-03-16 12:27 UTC, mkatsanto requested changes
I think the issue is not as straightforward. The temp file removal cause an issue during testing since some md5s cannot be compared: This could be solved by indeed activating or deactivating the temp flag. However, in that case there should be a second test, making sure that the temp flag works appropriately and remove those md5s that are actually temp files.
So there are 3 things overall:

- [X] Default snakemake behaviour should be to remove temp files 
- [X] Disable the temp removal from the tests
- [ ] Have extra tests to make sure the workflow runs successfully when you remove the temp flag (check only md5s that remain after temp removal)

2022-03-16 18:28 UTC, AngryMaciek commented
@mkatsanto 
I am not convinced this is a proper approach... I don't think it is our job to test that _Snakemake_ flags are implemented correctly. Following that logic we may as well test `nohooks`, `keep-going` etc. Given that `False` for `notemp` is the default behavior I think it is safe to assume that because we do not observe any missing-files-error while comparing md5 sums that must mean that the command line flag in the test scripts overwrote the profile and everything is as it should be.

2022-03-16 20:50 UTC, mkatsanto commented
@AngryMaciek
In the issue #25 we say that:`  However, if we get rid of it then during the pipeline execution multiqc fails - it does not find files which it expects... They are probably removed due to the temp() mechanism.`
So the issue was that at some point we probably eliminate something that is explicitly called in the multiqc rule. I would guess that this is some folder probably, because if the file is not explicitly called maybe this temp flag does not realise we actually need this file. Unless you test with the temp removal I do not see how you can ensure you are not removing something you shouldn't.

2022-03-17 11:20 UTC, mkatsanto approved these changes

2022-03-17 11:21 UTC, merged